version: '3.7'

volumes:
  jenkins_home:
  gitlab_config:
  gitlab_logs:
  gitlab_data:

networks:
  docker-ci-network:
    driver: bridge

services:
  jenkins:
    build:
      context: .
      dockerfile: dockerfile-jenkins
    image: theopendle/jenkins-ci:1.0.0
    container_name: ${COMPOSE_PROJECT_NAME}-jenkins
    ports:
      - ${JENKINS_PORT_MAPPING}
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - docker-ci-network

  sonarqube:
    build:
      context: .
      dockerfile: dockerfile-sonarqube
    image: theopendle/sonarqube-ci:1.0.0
    container_name: ${COMPOSE_PROJECT_NAME}-sonarqube
    ports:
      - ${SONAR_PORT_MAPPING}
    networks:
      - docker-ci-network
