version: '3.7'

volumes:
  jenkins-home:
  sonarqube-data:
  sonarqube-extensions:

networks:
  docker-ci-network:
    driver: bridge

services:
  jenkins:
    build:
      context: .
      dockerfile: dockerfile-jenkins
    image: theopendle/jenkins-ci:1.0.0
    container_name: ${COMPOSE_PROJECT_NAME}-jenkins
    ports:
      - ${JENKINS_PORT_MAPPING}
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - docker-ci-network

  sonarqube:
    build: sonarqube:latest
    image: theopendle/sonarqube-ci:1.0.0
    container_name: ${COMPOSE_PROJECT_NAME}-sonarqube
    ports:
      - ${SONAR_PORT_MAPPING}
    networks:
      - docker-ci-network
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
